captainVersion: 4
services:
    $$cap_appname:
        image: bitnami/odoo:latest
        #depends_on:
            #- $$cap_appname-db
        volumes:
            - $$cap_appname-odoo-web-data:/var/lib/odoo
            - $$cap_appname-config:/etc/odoo
            - $$cap_appname-addons:/mnt/extra-addons
        restart: always
        environment:
            #POSTGRES_PASSWORD: $$cap_postgres_password
            #HOST: srv-captain--$$cap_appname-db        
            ODOO_EMAIL: devops1@rg1.us
            ODOO_PASSWORD: Devops123!!
            ODOO_LOAD_DEMO_DATA: no
            ODOO_SKIP_BOOTSTRAP: yes
            ODOO_DATABASE_HOST: 35.231.253.154
            ODOO_DATABASE_PORT_NUMBER: 5432
            ODOO_DATABASE_ADMIN_USER: postgres
            ODOO_DATABASE_ADMIN_PASSWORD: Y7C5SPjLhqmF
            ODOO_DATABASE_NAME: bitnami_odoo
            ODOO_DATABASE_USER: bn_odoo
            ODOO_DATABASE_PASSWORD: 0676e3492c403b6653f8cd4a0a61facb085bbf5002a698a6ad1010917244ad00
            ALLOW_EMPTY_PASSWORD: yes

        caproverExtra:
            containerHttpPort: '8069'
